version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/movies.db:/app/movies.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_TMDB_API_KEY=YOUR_API_KEY
      - NEXT_PUBLIC_TMDB_API_URL=https://api.themoviedb.org/3
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
